name: Deploy New Feature to Customers
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prod
permissions:
  actions: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'qa' && (startsWith(github.ref_name, 'rel/') || startsWith(github.ref_name, 'hotfix/'))
    outputs:
      short_sha: ${{ steps.get_sha.outputs.short_sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # - name: Step 1 - Set value
      #   run: echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
      
      - name: Get branch name
        id: get_branch
        run: |
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          
      - name: Step 2 - Use value
        run: echo "The variable is $BRANCH"
        
      # - name: Get short SHA
      #   id: get_sha
      #   run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      # - name: Use short SHA
      #   run: echo "Short SHA is ${{ steps.get_sha.outputs.short_sha }}"
      - name: Get short commit ID
        id: get_commit
        run: |
          SHORT_COMMIT_ID=$(git rev-parse --short HEAD)
          echo "SHORT_COMMIT_ID=$SHORT_COMMIT_ID" >> $GITHUB_ENV

      # Step 3: Use the short commit ID in another step
      - name: Use short commit ID
        run: |
          echo "The short commit ID is: $SHORT_COMMIT_ID"
          
      - name: Print branch name
        run: |
          BRANCH=${{ github.ref_name }}
          echo "Current branch: $BRANCH"
          echo "Current branch (using GITHUB_REF): ${GITHUB_REF##*/}"

      - name: branch name
        run: |
          echo "From above step: $BRANCH"
